apiVersion: v2
name: argocd
description: Custom chart form argocd
version: 1.1.0
appVersion: v1.9.6
dependencies:
  - name: argo-cd
    repository: https://argoproj.github.io/argo-helm
    version: 9.1.6
